digitalskola_project2_data_transform:
  outputs:
    dev:
      dbname: "{{ env_var('DBT_DBNAME') }}"
      host: "{{ env_var('DBT_HOST') }}"
      pass: "{{ env_var('DBT_PASSWORD') }}"
      port: "{{ env_var('DBT_PORT') | int }}"
      schema: dbt_dev
      threads: 1
      type: postgres
      user: "{{ env_var('DBT_USER') }}"
    prod:
      dbname: "{{ env_var('DBT_DBNAME') }}"
      host: "{{ env_var('DBT_HOST') }}"
      pass: "{{ env_var('DBT_PASSWORD') }}"
      port: "{{ env_var('DBT_PORT') | int }}"
      schema: dbt
      threads: 1
      type: postgres
      user: "{{ env_var('DBT_USER') }}"
  target: dev